services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: cafe_order
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cafe_order"]
      interval: 5s
      timeout: 3s
      retries: 20

  server:
    build: ./server
    environment:
      DATABASE_URL: postgresql://postgres:123@db:5432/cafe_order?schema=public
      PORT: 4000
      CLIENT_ORIGIN: http://localhost:5173

      # your seed.js supports these
      SEED_ENABLED: "true"
      SEED_RESET: "false"
    ports:
      - "4000:4000"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -lc "
        npx prisma migrate deploy &&
        npx prisma db seed &&
        node index.js
      "

  client:
    build: ./client
    environment:
      VITE_API_URL: http://localhost:4000
    depends_on:
      - server
    ports:
      - "5173:5173"

volumes:
  db_data: